// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_log_id_ from "./routes/api/log/[id].ts";
import * as $api_log_add from "./routes/api/log/add.ts";
import * as $api_log_edit from "./routes/api/log/edit.ts";
import * as $api_log_index from "./routes/api/log/index.ts";
import * as $api_log_monthly_counts from "./routes/api/log/monthly_counts.ts";
import * as $api_markdown_render from "./routes/api/markdown/render.ts";
import * as $create_index from "./routes/create/index.tsx";
import * as $edit_id_ from "./routes/edit/[id].tsx";
import * as $index from "./routes/index.tsx";
import * as $ArticleForm from "./islands/ArticleForm.tsx";
import * as $ArticleItem from "./islands/ArticleItem.tsx";
import * as $ArticlesSideContent from "./islands/ArticlesSideContent.tsx";
import * as $CreateForm from "./islands/CreateForm.tsx";
import * as $EditForm from "./islands/EditForm.tsx";
import * as $SearchQueryForm from "./islands/SearchQueryForm.tsx";
import * as $SortDropdown from "./islands/SortDropdown.tsx";
import * as $SortOrderToggle from "./islands/SortOrderToggle.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/log/[id].ts": $api_log_id_,
    "./routes/api/log/add.ts": $api_log_add,
    "./routes/api/log/edit.ts": $api_log_edit,
    "./routes/api/log/index.ts": $api_log_index,
    "./routes/api/log/monthly_counts.ts": $api_log_monthly_counts,
    "./routes/api/markdown/render.ts": $api_markdown_render,
    "./routes/create/index.tsx": $create_index,
    "./routes/edit/[id].tsx": $edit_id_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/ArticleForm.tsx": $ArticleForm,
    "./islands/ArticleItem.tsx": $ArticleItem,
    "./islands/ArticlesSideContent.tsx": $ArticlesSideContent,
    "./islands/CreateForm.tsx": $CreateForm,
    "./islands/EditForm.tsx": $EditForm,
    "./islands/SearchQueryForm.tsx": $SearchQueryForm,
    "./islands/SortDropdown.tsx": $SortDropdown,
    "./islands/SortOrderToggle.tsx": $SortOrderToggle,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
