// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_logs from "./routes/api/logs.ts";
import * as $create_index from "./routes/create/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $CreateForm from "./islands/CreateForm.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/logs.ts": $api_logs,
    "./routes/create/index.tsx": $create_index,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/CreateForm.tsx": $CreateForm,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
